pad_left: false
reverse_input: false
embedding_dim: 30
bidirectional: true
cell_type: LSTM
cell_size: 16
num_residual: 1
num_layers: 3
attention_type: luong
attention_layer_size: 32
optimizer: AdamOptimizer
optimizer_kwargs:
  learning_rate: 0.1

# training options
batch_size: 200
max_epochs: 100000
early_stopping_threshold: 0.01
patience: 10

# saving options
save_model: True
model_dir: exps/small
