reverse_input: false
embedding_dim: 10
bidirectional: false
cell_type: LSTM
cell_size: 8
num_residual: 0
num_layers: 1
attention_type: luong
attention_layer_size: 16
optimizer: AdamOptimizer
optimizer_kwargs:
  learning_rate: 0.1

# training options
batch_size: 5
max_epochs: 10
early_stopping_threshold: 0.1
patience: 2

# saving options
save_model: True
model_dir: models/toy
